keys:
  - &maxs-macbook-pro age1crme8auc0sjgeu0r85w5lt04ey59me7jx4945zje4lnj3ctf2pzs8tc288
  - &kopf3-NB-26 age13242rt3uhlc6k7p6un8lxy86m3wysjclwntwr8v5pl9fshdf8suqxvqps2
creation_rules:
  - path_regex: secrets/common.yaml
    key_groups:
      - age:
        - *maxs-macbook-pro
        - *kopf3-NB-26
