keys:
  - &maxs-macbook-pro age1crme8auc0sjgeu0r85w5lt04ey59me7jx4945zje4lnj3ctf2pzs8tc288
  - &kopf3-NB-26 age13242rt3uhlc6k7p6un8lxy86m3wysjclwntwr8v5pl9fshdf8suqxvqps2
  - &maxdata age1s44mfk6jem5nz0nnt0kp0l59tdhzns0s6dtt97gwxf7xyxh2240sj5mw4m
  - &ionos age100thyt62mn4gyw90thmz5rzqtzd5d9jga4gtljvylcnuu3cawscqcqtmah
  - &k3s-node1 age10jf99q3ygydry992384x0sc6qh4l7auvyun92arvsm2mm5lttvwqf2z3t3
  - &k3s-node2 age135dpxcvascd3clh3dczmx827z9nn26f0gtcsa9e0nrjpj8eht55slnh2zj
  - &k3s-node3 age1jcxzku7rqksy8juwtj6jvmvfyt63ywa386r3dj59cu2u35cgzqts4jxk0c
creation_rules:
  - path_regex: secrets/common.yaml
    key_groups:
      - age:
        - *maxs-macbook-pro
        - *kopf3-NB-26
        - *maxdata
        - *ionos
  - path_regex: secrets/k3s.yaml
    key_groups:
      - age:
          - *maxs-macbook-pro
          - *maxdata
          - *ionos
          - *k3s-node1
          - *k3s-node2
          - *k3s-node3
